version: "3.8"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
            - 3308:3306

    backend:
        build: ./
        ports:
            - 5000:5000
        environment:
            - ASPNETCORE_URLS=http://+:5000
        depends_on:
            - db

    reverse-proxy:
        image: nginx:latest
        container_name: reverse_proxy
        depends_on:
            - backend
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80