version: "3.8"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
        volumes:
      # this style the data is attached to the container /var/lib/mysql directory ##
      # this style is storing the data on the host machine (the machine where you run docker-compose up) ##
            - ./serverdatabase:/var/lib/mysql # this will creata a folder "serverdatabase" automatically and copies the contents of /var/lib/mysql ##
        ports:
            - 3308:3306

    backend:
        build: ./
        ports:
            - 5000:5000
        environment:
            - ASPNETCORE_URLS=http://+:5000
        depends_on:
            - db

    backendv2:
            build: ./
            ports:
                - 5001:5001
            environment:
                - ASPNETCORE_URLS=http://+:5001
            depends_on:
                - db

    reverse-proxy:
        image: nginx:latest
        container_name: reverse_proxy
        depends_on:
            - backend
            - backendv2
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80